import { Question } from './types';

export const questions: Question[] = [
  {
    id: 1,
    emoji: '😴',
    question: 'Do you sleep 7–8 hours per night?',
    description: 'Quality sleep boosts immunity and mental clarity.',
    category: 'sleep',
    positive: true,
  },
  {
    id: 2,
    emoji: '💧',
    question: 'Do you drink at least 8 glasses of water daily?',
    description: 'Hydration keeps your skin, brain, and organs healthy.',
    category: 'water',
    positive: true,
  },
  {
    id: 3,
    emoji: '🚶',
    question: 'Do you walk at least 30 minutes a day?',
    description: 'Walking improves cardiovascular health and mood.',
    category: 'walking',
    positive: true,
  },
  {
    id: 4,
    emoji: '🏋️',
    question: 'Do you exercise 3+ times per week?',
    description: 'Regular exercise strengthens muscles and bones.',
    category: 'exercise',
    positive: true,
  },
  {
    id: 5,
    emoji: '🚭',
    question: 'Are you a non‑smoker?',
    description: 'Smoking is a leading cause of preventable disease.',
    category: 'smoking',
    positive: false, // 'no' is healthy
  },
  {
    id: 6,
    emoji: '🍷',
    question: 'Do you drink alcohol less than 2 times per week?',
    description: 'Moderate drinking lowers health risks.',
    category: 'alcohol',
    positive: false,
  },
  {
    id: 7,
    emoji: '🧠',
    question: 'Do you manage stress well?',
    description: 'Stress management improves heart health and longevity.',
    category: 'stress',
    positive: true,
  },
  {
    id: 8,
    emoji: '🥦',
    question: 'Do you eat vegetables daily?',
    description: 'Vegetables provide essential vitamins and fiber.',
    category: 'vegetables',
    positive: true,
  },
  {
    id: 9,
    emoji: '🍎',
    question: 'Do you eat fruits daily?',
    description: 'Fruits are packed with antioxidants and nutrients.',
    category: 'fruits',
    positive: true,
  },
  {
    id: 10,
    emoji: '🍬',
    question: 'Do you limit added sugar intake?',
    description: 'Too much sugar leads to obesity and diabetes.',
    category: 'sugar',
    positive: false,
  },
  {
    id: 11,
    emoji: '🍔',
    question: 'Do you eat fast food less than once a week?',
    description: 'Fast food is high in calories and low in nutrients.',
    category: 'fastfood',
    positive: false,
  },
  {
    id: 12,
    emoji: '⚖️',
    question: 'Is your weight within a healthy range?',
    description: 'Maintaining a healthy weight reduces chronic disease risk.',
    category: 'weight',
    positive: true,
  },
  {
    id: 13,
    emoji: '⚡',
    question: 'Do you feel energetic throughout the day?',
    description: 'Good energy levels reflect overall well‑being.',
    category: 'energy',
    positive: true,
  },
  {
    id: 14,
    emoji: '📱',
    question: 'Do you limit screen time to less than 3 hours/day?',
    description: 'Excessive screen time strains eyes and disrupts sleep.',
    category: 'screentime',
    positive: false,
  },
  {
    id: 15,
    emoji: '🧘',
    question: 'Do you practice mental wellness activities?',
    description: 'Meditation, journaling, or hobbies boost mental health.',
    category: 'mental',
    positive: true,
  },
];