export const PRODUCTS = [
  {
    id: 1,
    name: "Chyawanprash",
    price: "₹341",
    originalPrice: "₹450",
    discount: "24% off",
    image: "🍯",
    link: "https://amzn.to/3OXMbVf",
    description: "Dabur Khajurprash - 900g | 3X Immunity Action | Supports Healthy Haemoglobin Levels | Helps Fight Iron Deficiency | 40+ Chyawanprash Herbs | Natural Source of Iron | Goodness of Khajur & Giloy",
    category: "health",
    barcode: "8901234567893"
  },
  {
    id: 2,
    name: "Kesh Kanti Advance Herbal",
    price: "₹263",
    originalPrice: "₹356",
    discount: "26% off",
    image: "👱‍♀️",
    link: "https://amzn.to/4cXveCA",
    description: "Patanjali Kesh Kanti Advance Herbal Hair Expert Oil 100ml, Stronger & Longer Hair for Women & Men, Nourishing Hair Oil Enriched with Amla, Reetha, Kalonji & Shikakai",
    category: "Beauty",
    barcode: "8901234567894"
  },
  {
    id: 3,
    name: "Himalaya Wellness Tablets",
    price: "₹212",
    originalPrice: "₹260",
    discount: "18% off",
    image: "🌿",
    link: "https://amzn.to/429EApJ",
    description: "Himalaya Wellness Pure Herbs Skin Wellness Tablets - 60 Count (Neem)",
    category: "skincare",
    barcode: "8901234567890"
  },
  {
    id: 4,
    name: "Zandu Pancharishta",
    price: "₹169",
    originalPrice: "₹215",
    discount: "21% off",
    image: "🍊",
    link: "https://amzn.to/4eSVIrg",
    description: "Zandu Pancharishta Ayurvedic Digestive Tonic 650ML | Relief from Regular Gas, Bloating, Acidity & Indigestion From the Root",
    category: "Health",
    barcode: "8901234567891"
  },
  {
    id: 5,
    name: "Ashwagandha Churna",
    price: "₹135",
    originalPrice: "₹180",
    discount: "25% off",
    image: "🌱",
    link: "https://amzn.to/4dgizfa",
    description: "Stress relief, immunity booster, energy",
    category: "supplements",
    barcode: "8901234567892"
  },
  {
    id: 6,
    name: "Tulsi Ginger",
    price: "₹217",
    originalPrice: "₹245",
    discount: "11% off",
    image: "🟡",
    link: "https://amzn.to/4tIBjtL",
    description: "A TATA Product - Organic India Tulsi Ginger - 25 Tea Bags, Rich in Antioxidants, Supports Digestion, Stress Relieving, Helps Boost Metabolism, Caffeine-Free, Whole Herbs Certified Organic",
    category: "Health",
    barcode: "8901234567895"
  },
  {
    id: 7,
    name: "Sri Sri TATTVA",
    price: "₹444",
    originalPrice: "₹556",
    discount: "14% off",
    image: "🌿",
    link: "https://amzn.to/4w03PZd",
    description: "Sri Sri Tattva Chocolate Ojasvita | For Sharp Mind and Healthy Body | Milk Mix | Goodness of 7 Herbs| Immunity Booster – 1kg Pet Jar",
    category: "health",
    barcode: "8901234567896"
  },
];